deploy:
  provider: cloudfoundry
  api: https://api.cf.skyscapecloud.com
  username: nhines@skyscapecloud.com
  password:
    secure: LgOHwSzqWj7r+R8g7CsQQ5e0jQvrWU2CUEhYzvpmgGbLzVQnv8ExhrQ3pR5xLydigrYGSnKNmxgARebBYPa+/JPcnFdFYt9Yh8eRycbKLc1teBaSAhGseGansLauaWoNqhOrsMZx0cU9M+pHqJjelMN3FtxyrKfrvlNWuVLAgus=
  organization: skyscape
  space: demo
  on:
    repo: SkyscapeDemo/SimpleNodeApp
    branch: master
    